-- 코드를 입력하세요
SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
LEFT JOIN ANIMAL_INS AI  ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.DATETIME IS NULL
ORDER BY AO.ANIMAL_ID, AO.NAME;



# SELECT A.ANIMAL_ID, A.NAME
# FROM ANIMAL_OUTS A
# LEFT JOIN ANIMAL_INS B
# ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE B.DATETIME IS NULL
# ORDER BY A.ANIMAL_ID, A.NAME;