-- 코드를 입력하세요
SELECT FO.PRODUCT_ID, PRODUCT_NAME,  SUM(PRICE*AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN FOOD_ORDER FO ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC